#!/usr/bin/env python3
"""
Q1 crepant-resolution certificate from q1_final_q5style_report.pdf.

This module records the paper's double-octic model in P^3_{a,b,c,d}, compares it
with the older repository Q1 octic, and writes a structured resolution ledger.
The atlas is intentionally formal: each blowup chart is represented by the
standard affine substitution for a center generated by local equations
f_1,...,f_r:

    chart f_i != 0:  f_j = f_i*u_j  for j != i.

For the double cover R^2 = D, a crepant center of branch multiplicity m uses
R = f_i^floor(m/2) * R_i and the chart branch equation is divided by
f_i^(2*floor(m/2)).
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, asdict
from pathlib import Path

from crepant_resolver import count_double_cover, parse_polynomial


PAPER_VARIABLES = ("a", "b", "c", "d")

Q3 = "a*d*(b+c-d)"

Q4 = (
    "a^2*b*c+a^2*b*d+a^2*c^2-a^2*c*d+a*b^2*d-a*b*c^2"
    "+a*b*c*d-2*a*b*d^2-2*a*c^2*d+3*a*c*d^2-a*d^3"
    "+b*c^2*d-2*b*c*d^2+b*d^3"
)

Q5 = (
    "a^3*b*c+a^2*b^2*d-a^2*b*c^2-a^2*b*c*d-a*b^2*d^2"
    "+2*a*b*c*d^2-a*b*d^3-b^2*c*d^2+b^2*d^3"
)

PAPER_DELTA = f"({Q4})^2-4*({Q3})*({Q5})"


@dataclass(frozen=True)
class Center:
    id: str
    stage: str
    kind: str
    codimension: int
    branch_multiplicity: int
    equations: tuple[str, ...]
    repeat: int = 1
    status: str = "crepant"
    note: str = ""

    @property
    def discrepancy_term(self) -> int:
        return self.codimension - 1 - self.branch_multiplicity // 2

    @property
    def chart_count_per_blowup(self) -> int:
        return len(self.equations)

    @property
    def total_chart_count_if_expanded(self) -> int:
        return self.chart_count_per_blowup ** self.repeat


@dataclass(frozen=True)
class SmallResolutionDivisor:
    id: str
    order: int
    equations: tuple[str, str]
    nodes_resolved: tuple[str, ...]


BRANCH_LINES = (
    Center("L1", "old branch line chains", "curve", 2, 2, ("a", "b"), 4, note="generic cA8 chain"),
    Center("L2", "old branch line chains", "curve", 2, 2, ("a-b", "c"), 2, note="generic cA4 chain"),
    Center("L3", "old branch line chains", "curve", 2, 2, ("a", "d"), 4, note="generic cA7 chain"),
    Center("L4", "old branch line chains", "curve", 2, 2, ("b", "c-d"), 4, note="generic cA8 chain"),
    Center("L5", "old branch line chains", "curve", 2, 2, ("a", "c-d"), 1, note="generic cA1 chain"),
    Center("L6", "old branch line chains", "curve", 2, 2, ("c", "d"), 4, note="generic cA7 chain"),
    Center("L7", "old branch line chains", "curve", 2, 2, ("a-d", "b+c-d"), 1, note="generic cA1 chain"),
)

POINTS = (
    Center("P13", "multiplicity-four points", "point", 3, 4, ("a", "b", "d"), note="[0:0:1:0]"),
    Center("P145", "multiplicity-four points", "point", 3, 4, ("a", "b", "c-d"), note="[0:0:1:1]"),
    Center("P27", "multiplicity-four points", "point", 3, 4, ("a-d", "b+c-d", "c"), note="[1:0:0:1] up to scale"),
    Center("P356", "multiplicity-four points", "point", 3, 4, ("a", "c", "d"), note="[0:1:0:0]"),
    Center("P46", "multiplicity-four points", "point", 3, 4, ("b", "c-d", "c"), note="[1:0:0:0] in local P46 chart"),
    Center("P47", "multiplicity-four points", "point", 3, 4, ("b", "c-d", "a-d"), note="[1:0:1:1]"),
)

EXCEPTIONAL_CURVES = (
    Center("E145_x", "exceptional curves after point blow-ups", "curve", 2, 2, ("x", "exceptional_145"), note="local chart center from Table 5"),
    Center("E145_z", "exceptional curves after point blow-ups", "curve", 2, 2, ("z", "exceptional_145"), note="local chart center from Table 5"),
    Center("E356_x", "exceptional curves after point blow-ups", "curve", 2, 2, ("x", "exceptional_356"), note="local chart center from Table 5"),
    Center("E356_z", "exceptional curves after point blow-ups", "curve", 2, 2, ("z", "exceptional_356"), note="local chart center from Table 5"),
    Center("E46_q", "exceptional curves after point blow-ups", "curve", 2, 2, ("q", "exceptional_46"), note="local chart center from Table 5"),
)

GAMMA_CENTERS = (
    Center("Gamma_46", "residual Gamma_46", "curve", 2, 2, ("e", "(T-1)*(r-e)+T"), note="main residual curve"),
    Center("Gamma_46_T1_a", "Gamma_46 endpoint T=1", "curve", 2, 2, ("n", "tau"), note="first finite endpoint blowup"),
    Center("Gamma_46_T1_b", "Gamma_46 endpoint T=1", "curve", 2, 2, ("m", "tau"), note="second finite endpoint blowup"),
    Center("Gamma_46_Tinf_a", "Gamma_46 endpoint T=infinity", "curve", 2, 2, ("e", "K"), note="first infinite endpoint blowup"),
    Center("Gamma_46_Tinf_b", "Gamma_46 endpoint T=infinity", "curve", 2, 2, ("m", "U"), note="second infinite endpoint blowup"),
)

SMALL_RESOLUTIONS = (
    SmallResolutionDivisor(
        "Dab_plus",
        1,
        ("b-a", "R-a*c*(a^2+c*d-d^2)"),
        ("N13_0",),
    ),
    SmallResolutionDivisor(
        "Db_minus",
        2,
        ("b", "R+a*(c-d)*(a*c-2*c*d+d^2)"),
        ("N13_half", "N46_0"),
    ),
    SmallResolutionDivisor(
        "Dd_minus",
        3,
        ("d", "R+a*c*(a*b+a*c-b*c)"),
        ("N46_qt",),
    ),
)

NODES = ("N13_0", "N13_half", "N46_0", "N46_qt")
KULIKOV_FIBERS = {"0": "III", "2": "I", "-1": "II", "infinity": "III"}
DEFAULT_COUNT_PRIMES = (3, 5, 7, 11, 107)


def all_centers() -> tuple[Center, ...]:
    return BRANCH_LINES + POINTS + EXCEPTIONAL_CURVES + GAMMA_CENTERS


def standard_charts(center: Center) -> list[dict]:
    charts = []
    for pivot_index, pivot in enumerate(center.equations):
        substitutions = []
        for idx, equation in enumerate(center.equations):
            if idx == pivot_index:
                continue
            substitutions.append(f"{equation} = ({pivot})*u_{center.id}_{idx}")
        charts.append(
            {
                "pivot": pivot,
                "substitutions": substitutions,
                "cover_variable": f"R = ({pivot})^{center.branch_multiplicity//2}*R_{center.id}",
                "branch_transform": f"D_chart = substitute(D, chart_map)/({pivot})^{center.branch_multiplicity}",
            }
        )
    return charts


def expanded_affine_chart_tree(centers: tuple[Center, ...]) -> list[dict]:
    """List every blow-up occurrence with its standard affine charts.

    Repeated cA_n line chains are deliberately expanded as L_i_1, ..., L_i_r so
    downstream code has a literal ordered tree to traverse without interpreting
    the repeat field.
    """
    tree = []
    order = 0
    for center in centers:
        for repeat_index in range(1, center.repeat + 1):
            order += 1
            occurrence = {
                **asdict(center),
                "id": f"{center.id}_{repeat_index}" if center.repeat > 1 else center.id,
                "base_center_id": center.id,
                "repeat_index": repeat_index,
                "order": order,
                "discrepancy_term": center.discrepancy_term,
            }
            occurrence["standard_affine_charts"] = standard_charts(
                Center(
                    id=occurrence["id"],
                    stage=center.stage,
                    kind=center.kind,
                    codimension=center.codimension,
                    branch_multiplicity=center.branch_multiplicity,
                    equations=center.equations,
                    repeat=1,
                    status=center.status,
                    note=center.note,
                )
            )
            tree.append(occurrence)
    return tree


def q1_count_data(primes: tuple[int, ...] = DEFAULT_COUNT_PRIMES) -> dict:
    poly = parse_polynomial(PAPER_DELTA, variables=PAPER_VARIABLES)
    rows = []
    for p in primes:
        singular = count_double_cover(poly, p)
        correction = 58 * p * p + 82 * p
        resolved = singular + correction
        trace = 1 + p**3 + 66 * (p * p + p) - resolved
        rows.append(
            {
                "p": p,
                "singular_model_count": singular,
                "crepant_correction": correction,
                "resolved_count": resolved,
                "trace_a_p": trace,
                "good_prime": p not in {2, 3, 13},
            }
        )
    return {
        "formula": "#X1(F_p) = #Y0(F_p) + 58*p^2 + 82*p",
        "trace_formula": "a_p = 1 + p^3 + 66*(p^2+p) - #X1(F_p)",
        "bad_primes": [2, 3, 13],
        "rows": rows,
        "symbolic_decomposition": {
            "total": "58*p^2 + 82*p",
            "report_components": [
                "old branch-line chains",
                "six multiplicity-four point blow-ups",
                "five exceptional curve blow-ups",
                "Gamma_46 main curve and endpoint chains",
                "four projective small resolutions",
            ],
            "Gamma_46_main": "p^2 + 4*p",
        },
    }


def ledger(primes: tuple[int, ...] = DEFAULT_COUNT_PRIMES) -> dict:
    centers = all_centers()
    divisorial_count = sum(center.repeat for center in centers)
    affine_tree = expanded_affine_chart_tree(centers)
    return {
        "model": {
            "ambient": "P^3_{a,b,c,d}",
            "double_cover": "R^2 = Delta",
            "projection_center": "[1:1:0:1:0]",
            "projection_substitution": {
                "X0": "u+a",
                "X1": "u+b",
                "X2": "c",
                "X3": "u",
                "X4": "d",
            },
            "projected_quadratic": "u^2*q3 + u*q4 + q5",
            "q3": Q3,
            "q4": Q4,
            "q5": Q5,
            "Delta": PAPER_DELTA,
        },
        "model_search": {
            "chart": "projection from [1:1:0:1:0]",
            "quadratic_variable": "u",
            "p3_variables_from_projective_coordinates": "a,b,c,d",
            "u_power_removed_from_discriminant": 0,
            "selected_candidate_index": "project-report projection",
            "candidate_count": "not from chart search",
        },
        "isomorphism_with_repository_q1_octic": {
            "status": "not_projectively_isomorphic",
            "reason": "Macaulay2 singular-locus signatures differ: paper model has seven singular lines plus one point; repository K3_Fibration octic has eight singular lines plus one point.",
            "certificate_script": "codexCrepeantResolutions/q1_compare_models.m2",
        },
        "centers": [
            {
                **asdict(center),
                "discrepancy_term": center.discrepancy_term,
                "standard_affine_charts": standard_charts(center),
            }
            for center in centers
        ],
        "affine_chart_tree": affine_tree,
        "explicit_affine_chart_count": sum(len(node["standard_affine_charts"]) for node in affine_tree),
        "divisorial_blowup_count": divisorial_count,
        "small_resolution_divisors": [asdict(divisor) for divisor in SMALL_RESOLUTIONS],
        "ordinary_double_points": list(NODES),
        "picard_rank": 66,
        "hodge_numbers": {"h11": 66, "h21": 0},
        "euler_characteristic": 132,
        "bad_primes": [2, 3, 13],
        "finite_field_count_formula": "#X1(F_p) = 1 + p^3 + 66*(p^2+p) - a_p(13.4.a.a), for p not in {2,3,13}",
        "point_count_correction": q1_count_data(primes),
        "singular_kulikov_fibers": KULIKOV_FIBERS,
        "atlas_note": (
            "affine_chart_tree expands repeated line-chain blow-ups into individual ordered "
            "occurrences. Each occurrence lists every standard affine chart for that blow-up."
        ),
    }


def q1_m2_source() -> str:
    return "\n".join(
        [
            "-- Q1 branch octic from q1_final_q5style_report.pdf.",
            "-- Projection center: [1:1:0:1:0].",
            "-- Coordinates are P^3_{a,b,c,d}; the double cover is R^2 = Delta.",
            "",
            "R = QQ[a,b,c,d]",
            f"q3 = {Q3}",
            f"q4 = {Q4}",
            f"q5 = {Q5}",
            "Delta = q4^2 - 4*q3*q5",
            f"-- D = {PAPER_DELTA}",
            "",
            "singularIdeal = () -> (",
            "    irr := ideal(a,b,c,d);",
            "    saturate(ideal(Delta) + ideal(diff(a,Delta), diff(b,Delta), diff(c,Delta), diff(d,Delta)), irr)",
            ")",
            "singularComponents = () -> decompose singularIdeal()",
            "",
        ]
    )


def write_case_outputs(out_dir: Path, case: str = "Q1", primes: tuple[int, ...] = DEFAULT_COUNT_PRIMES) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    data = ledger(primes)
    data["case"] = case
    data["status"] = "crepant_resolution"
    data["path"] = "q1_final_q5style_report.pdf"
    (out_dir / f"{case}.json").write_text(json.dumps(data, indent=2, sort_keys=True))
    (out_dir / f"{case}.m2").write_text(q1_m2_source())

    lines = [
        f"# {case}",
        "",
        "Model: `R^2 = Delta(a,b,c,d)` in `P(1,1,1,1,4)`.",
        "Projection center: `[1:1:0:1:0]` with `X0=u+a`, `X1=u+b`, `X2=c`, `X3=u`, `X4=d`.",
        "",
        "## Isomorphism Check",
        data["isomorphism_with_repository_q1_octic"]["reason"],
        "",
        "Run `M2 --script codexCrepeantResolutions/q1_compare_models.m2` for the certificate.",
        "",
        "## Resolution Ledger",
        f"Divisorial blowups: {data['divisorial_blowup_count']}",
        f"Small resolved ordinary double points: {len(data['ordinary_double_points'])}",
        f"Picard rank: {data['picard_rank']}",
        f"Bad primes: {', '.join(map(str, data['bad_primes']))}",
        f"Explicit affine blow-up charts: {data['explicit_affine_chart_count']}",
        "",
        "| Center | Stage | Kind | Repeat | codim | mult | crepant |",
        "| --- | --- | --- | ---: | ---: | ---: | ---: |",
    ]
    for center in data["centers"]:
        lines.append(
            f"| {center['id']} | {center['stage']} | {center['kind']} | {center['repeat']} | "
            f"{center['codimension']} | {center['branch_multiplicity']} | {center['discrepancy_term'] == 0} |"
        )
    lines += [
        "",
        "## Standard Affine Blowup Chart",
        "For a center with local equations `f_1,...,f_r`, the chart with pivot `f_i` uses "
        "`f_j = f_i*u_j` for `j != i`, `R = f_i^floor(m/2) R_i`, and "
        "`D_i = D(substituted)/f_i^m`.",
        "",
        "The JSON file records the expanded `affine_chart_tree`, with repeated line-chain blow-ups listed as individual ordered occurrences.",
        "",
        "## Point Counts",
        f"Correction: `{data['point_count_correction']['formula']}`.",
        "",
        "| p | #Y0(F_p) | correction | #X1(F_p) | a_p | good? |",
        "| ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for row in data["point_count_correction"]["rows"]:
        lines.append(
            f"| {row['p']} | {row['singular_model_count']} | {row['crepant_correction']} | "
            f"{row['resolved_count']} | {row['trace_a_p']} | {row['good_prime']} |"
        )
    lines += [
        "",
        "## Small Resolutions",
    ]
    for divisor in data["small_resolution_divisors"]:
        lines.append(
            f"- {divisor['id']}: `{divisor['equations'][0]}`, `{divisor['equations'][1]}`; "
            f"nodes {', '.join(divisor['nodes_resolved'])}"
        )
    lines += [
        "",
        "## Singular Kulikov Fibers",
    ]
    for parameter, fiber_type in data["singular_kulikov_fibers"].items():
        lines.append(f"- `r = {parameter}`: Type {fiber_type}")
    lines.append("")
    (out_dir / f"{case}.md").write_text("\n".join(lines))


def write_outputs(out_dir: Path, primes: tuple[int, ...] = DEFAULT_COUNT_PRIMES) -> None:
    write_case_outputs(out_dir, "Q1_paper_crepant_resolution", primes)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=Path("codexCrepeantResolutions/reports"))
    parser.add_argument("--case", default="Q1_paper_crepant_resolution")
    parser.add_argument("--primes", type=int, nargs="*", default=list(DEFAULT_COUNT_PRIMES))
    args = parser.parse_args()
    write_case_outputs(args.out, args.case, tuple(args.primes))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
